-- Run in Supabase SQL Editor.
create table if not exists public.roles (
    id bigint generated by default as identity primary key,
    name text not null unique
);

insert into public.roles (name)
values ('admin'), ('teacher'), ('student'), ('parent')
on conflict (name) do nothing;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    email text not null unique,
    password_hash text not null,
    person_id bigint,
    role_id bigint not null references public.roles(id),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

-- Upgrade the original users table without ever using its legacy password column.
alter table public.users add column if not exists username text;
alter table public.users add column if not exists password_hash text;
alter table public.users add column if not exists is_active boolean not null default true;
alter table public.users add column if not exists created_at timestamptz not null default now();
alter table public.users alter column person_id drop not null;

update public.users
set username = 'user_' || id::text
where username is null;

create unique index if not exists users_username_key on public.users (username);

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    name text not null,
    roll_number text not null unique,
    admission_date date,
    status text not null default 'active',
    created_at timestamptz not null default now()
);

alter table public.students add column if not exists admission_date date;
alter table public.students add column if not exists status text not null default 'active';
alter table public.students add column if not exists created_at timestamptz not null default now();

alter table public.users enable row level security;
alter table public.students enable row level security;

-- FastAPI uses the service-role client for ERP reads/writes. The service role
-- bypasses RLS; browser clients receive no direct write policy.
drop policy if exists "Allow anyone to insert students" on public.students;
drop policy if exists "Deny direct student inserts" on public.students;
create policy "Deny direct student inserts"
on public.students for insert
to anon, authenticated
with check (false);

-- No browser policy is created for public.users. Provisioning is server-only.
-- After legacy password hashes have been migrated, remove the old plaintext column:
-- alter table public.users drop column if exists password;